apiVersion: v1
kind: Service
metadata:
  name: secure-file-storage-service
spec:
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
  type: ClusterIP
  selector:
    app: secure-file-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-file-storage-deployment
spec:
  selector:
    matchLabels:
      app: secure-file-storage
  replicas: 1
  template:
    metadata:
      labels:
        app: secure-file-storage
    spec:
# Uncomment only if you are not deploying to the default namespace
# In this case, make sure to create a Docker registry secret
#      imagePullSecrets:
#        - name: $IMAGE_PULL_SECRET
      containers:
      - name: secure-file-storage-container
        image: us.icr.io/tmcguckin/simple-secure-file-storage:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        envFrom:
         - secretRef:
            name: secure-file-storage-credentials